export type Article = {
  slug: string;
  title: string;
  h1: string;
  description: string;
  date: string;
  image: string;
  alt: string;
  intro: string;
  body: { h: string; p: string }[];
  faq: { q: string; a: string }[];
  related: { to: string; label: string }[];
};

export const ARTICLES: Article[] = [
  {
    slug: "combien-coute-un-convoyage-automobile",
    title: "Combien coûte un convoyage automobile ?",
    h1: "Combien coûte un convoyage automobile ?",
    description: "Le prix d’un convoyage dépend de la distance, du véhicule, de la date et des options. Fourchette après coordonnées, depuis Quimper.",
    date: "2026-09-01",
    image: "/images/blog-tarif.jpg",
    alt: "Audi A4 Avant au péage, convoyage longue distance",
    intro: "Il n’existe pas de tarif unique. Un trajet Quimper–Brest n’a rien à voir avec un import Pologne. Voici ce qui fait le prix.",
    body: [
      { h: "Ce qui entre dans le calcul", p: "Distance, type de véhicule, urgence, week-end, Europe, options. Le retour du convoyeur est inclus. Les péages et le carburant du véhicule convoyé aussi." },
      { h: "Ce qui n’est pas affiché", p: "Pas de grille publique. Une fourchette basse et haute s’affiche après vos coordonnées. Prix indicatif, à confirmer." },
      { h: "Comment augmenter le panier, côté client", p: "Pack mise à la route, lavage, GPS, coffret. Vous composez. Vous ne payez pas ce que vous n’avez pas coché." },
    ],
    faq: [{ q: "Y a-t-il un minimum ?", a: "Oui, un forfait local. Le simulateur l’applique." }],
    related: [{ to: "/simulateur", label: "Simulateur" }, { to: "/pack-mise-a-la-route", label: "Packs" }],
  },
  {
    slug: "livrer-une-voiture-achetee-a-distance",
    title: "Comment faire livrer une voiture achetée à distance ?",
    h1: "Faire livrer une voiture achetée à distance",
    description: "Achat Leboncoin, mandataire, concession éloignée. Convoyage, état des lieux photo, remise à domicile depuis Quimper.",
    date: "2026-09-01",
    image: "/images/mission-308.jpg",
    alt: "Peugeot 308 prise en charge pour un achat à distance",
    intro: "Vous avez acheté. Reste la route. Un convoyeur évite le train, la location, la fatigue.",
    body: [
      { h: "Avant de partir", p: "Le véhicule doit être roulant, assuré, documents à bord. Sinon, ce n’est pas un convoyage en conduite." },
      { h: "Pendant", p: "État des lieux photo au départ. Option GPS. Vous n’êtes pas dans le véhicule. Vous recevez un compte-rendu." },
      { h: "À l’arrivée", p: "Clés en main propre, mise en main offerte. Pack lavage si vous voulez une remise propre." },
    ],
    faq: [{ q: "Puis-je payer après ?", a: "Non pour un particulier. Virement avant départ." }],
    related: [{ to: "/livraison-vehicule-particulier", label: "Particuliers" }, { to: "/simulateur", label: "Estimer" }],
  },
  {
    slug: "comment-fonctionne-le-convoyage-automobile",
    title: "Comment fonctionne le convoyage automobile ?",
    h1: "Comment fonctionne le convoyage automobile",
    description: "Prise en charge, conduite, état des lieux, remise. Le fonctionnement d’un convoyage depuis Quimper.",
    date: "2026-09-01",
    image: "/images/blog-processus.jpg",
    alt: "Chauffeur photographiant un véhicule avant le départ",
    intro: "Un convoyage est une conduite d’un point à un autre, documentée. Ce n’est ni un plateau, ni un taxi.",
    body: [
      { h: "Le socle", p: "Prise en charge, trajet, péages, carburant du véhicule, retour du convoyeur, photos, clés, mise en main." },
      { h: "Le protocole", p: "Avant, pendant, après. C’est le Protocole Clément. Preuve, pas improvisation." },
      { h: "Les limites", p: "Permis B, 3,5 t, roulant. Au-delà : autre métier." },
    ],
    faq: [{ q: "Combien de temps ?", a: "24 à 48 h en régional. J+2 à J+4 en Europe." }],
    related: [{ to: "/protocole-clement", label: "Protocole" }, { to: "/convoyage-automobile", label: "Convoyage" }],
  },
  {
    slug: "convoyage-ou-plateau",
    title: "Convoyage ou transport sur plateau : que choisir ?",
    h1: "Convoyage ou plateau ?",
    description: "Véhicule roulant : convoyage en conduite. Non-roulant, épave, trop large : plateau. Comment choisir.",
    date: "2026-09-01",
    image: "/images/blog-plateau.jpg",
    alt: "Peugeot 308 chargée sur un porte-voitures",
    intro: "Un véhicule roulant se conduit. Un véhicule non-roulant se charge. Ce n’est pas le même métier.",
    body: [
      { h: "Convoyage", p: "Moins cher sur longue distance qu’un plateau, plus rapide à organiser, le véhicule arrive avec des kilomètres de trajet. photos du véhicule indispensable." },
      { h: "Plateau", p: "Non-roulant, collection fragile, sinistre. Nous orientons. Nous ne le faisons pas." },
    ],
    faq: [{ q: "Et un jeune timer ?", a: "S’il est roulant, assuré, permis B : oui." }],
    related: [{ to: "/simulateur", label: "Estimer" }],
  },
  {
    slug: "preparer-une-voiture-avant-livraison",
    title: "Comment préparer une voiture avant livraison ?",
    h1: "Préparer une voiture avant livraison",
    description: "Lavage, niveaux, pneus, carburant, photos. Préparation réaliste avant remise client, depuis Quimper.",
    date: "2026-09-01",
    image: "/images/preparation-esthetique-vehicule.jpg",
    alt: "Préparation esthétique d’un véhicule avant remise",
    intro: "Une remise sale n’est pas une remise. La préparation n’est pas un detailing de concours.",
    body: [
      { h: "Le minimum", p: "Pression, niveaux, photos, documents. Pack Route, ou Pack Atelier côté professionnel." },
      { h: "Le standard concession", p: "Lavage intérieur et extérieur, désodorisation légère. Pack Sérénité, ou Pack Livraison client." },
      { h: "La remise soignée", p: "Traceur GPS cédé, 12 mois. Pack Sécurisé. Côté réseau : Pack Signature, coffret et protocole." },
    ],
    faq: [{ q: "Est-ce du detailing ?", a: "Non. Une préparation de remise, avec les moyens d’une mission de convoyage." }],
    related: [{ to: "/preparation-vehicule", label: "Préparation" }, { to: "/pack-mise-a-la-route", label: "Packs" }],
  },
  {
    slug: "etat-des-lieux-avant-convoyage",
    title: "État des lieux d’un véhicule avant convoyage",
    h1: "État des lieux avant convoyage",
    description: "Photos horodatées, compteur, carrosserie, intérieur. Pourquoi l’EDL protège vendeur, acheteur et convoyeur.",
    date: "2026-09-01",
    image: "/images/blog-edl.jpg",
    alt: "Contrôle visuel de carrosserie, photographie d’un impact",
    intro: "Sans photographies, c’est une discussion. Avec photographies, c’est un fait.",
    body: [
      { h: "Quoi photographier", p: "Extérieur, jantes, vitrages, intérieur, compteur, documents. Départ et arrivée." },
      { h: "Ce que ce n’est pas", p: "Pas une expertise. Pas un rapport opposable d’expert." },
    ],
    faq: [{ q: "Le client reçoit les photos ?", a: "Oui, avec le compte-rendu." }],
    related: [{ to: "/etat-des-lieux-convoyage", label: "EDL" }, { to: "/protocole-clement", label: "Protocole" }],
  },
  {
    slug: "acheter-une-voiture-a-distance-livraison",
    title: "Acheter une voiture à distance : organiser la livraison",
    h1: "Achat à distance : organiser la livraison",
    description: "Documents, paiement, convoyage, EDL. Comment faire livrer un véhicule acheté hors département.",
    date: "2026-09-01",
    image: "/images/mission-bmw-controle.jpg",
    alt: "Contrôle visuel d’une BMW avant achat à distance",
    intro: "L’annonce est belle. La route reste. Voici l’ordre.",
    body: [
      { h: "Papiers", p: "Carte grise, contrôle technique, assurance, mandat si besoin." },
      { h: "Argent", p: "Le convoyage se règle avant le départ pour un particulier." },
      { h: "Remise", p: "Chez vous, ou au garage. Mise en main offerte." },
    ],
    faq: [{ q: "Et si l’annonce ment ?", a: "On documente, on prévient, on n’embarque pas un doute." }],
    related: [{ to: "/convoyage-occasion", label: "Occasion" }, { to: "/simulateur", label: "Estimer" }],
  },
  {
    slug: "livrer-une-voiture-depuis-une-autre-region",
    title: "Comment faire livrer une voiture depuis une autre région ?",
    h1: "Livraison depuis une autre région",
    description: "Convoyage longue distance depuis Quimper. France entière. Délais, documents, fourchette.",
    date: "2026-09-01",
    image: "/images/mission-audi-a4.jpg",
    alt: "Audi A4 Avant en convoyage longue distance",
    intro: "Paris, Lyon, Bordeaux, Lille : le même standard qu’en Cornouaille. Le délai change. La remise, non.",
    body: [
      { h: "Délais", p: "J+1 à J+3 selon axe et charge. Urgent selon disponibilité." },
      { h: "Retour", p: "Le retour du convoyeur est dans le prix. Pas une surprise." },
    ],
    faq: [{ q: "La Corse ?", a: "Devis spécifique ferry." }],
    related: [{ to: "/livraison-vehicule", label: "France" }, { to: "/destinations", label: "Destinations" }],
  },
  {
    slug: "convoyage-automobile-bretagne",
    title: "Convoyage automobile en Bretagne",
    h1: "Convoyage automobile en Bretagne",
    description: "Convoyeur basé à Quimper. Finistère, Morbihan, Côtes-d’Armor, Ille-et-Vilaine. Livraison de véhicules en Bretagne.",
    date: "2026-09-01",
    image: "/images/blog-bretagne.jpg",
    alt: "Véhicule sur une route côtière en Bretagne",
    intro: "Quatre départements, une base. Quimper connaît les axes, les concessions, les créneaux.",
    body: [
      { h: "Le 29 d’abord", p: "Quimper, Brest, Concarneau, Bénodet, Douarnenez. Missions locales le jour même si le créneau tient." },
      { h: "Puis la Bretagne", p: "Lorient, Vannes, Rennes, Saint-Brieuc, Saint-Malo." },
    ],
    faq: [{ q: "Week-end en saison ?", a: "Oui. Les créneaux d’été se réservent." }],
    related: [{ to: "/convoyage-bretagne", label: "Bretagne" }, { to: "/livraison-voiture-finistere", label: "Finistère" }],
  },
  {
    slug: "convoyage-automobile-quimper",
    title: "Convoyage automobile à Quimper",
    h1: "Convoyage automobile à Quimper",
    description: "Convoyeur automobile à Quimper. Livraison locale, France, Europe. Base Cornouaille.",
    date: "2026-09-01",
    image: "/images/blog-quimper.jpg",
    alt: "BMW dans le centre historique de Quimper",
    intro: "Quimper n’est pas une antenne. C’est le siège. Clément y est.",
    body: [
      { h: "Local", p: "CT, carrosserie, courtoisie, livraison client. Le jour même si possible." },
      { h: "National et Europe", p: "Le véhicule part de Quimper, ou y arrive. Même protocole." },
    ],
    faq: [{ q: "Adresse ?", a: "Quimper, Finistère. Téléphone 06 24 04 85 73." }],
    related: [{ to: "/convoyage-quimper", label: "Page Quimper" }, { to: "/a-propos", label: "À propos" }],
  },
  {
    slug: "convoyage-voiture-electrique",
    title: "Convoyage d’une voiture électrique",
    h1: "Convoyage d’une voiture électrique",
    description: "Plan de recharge, autonomie, remise à un niveau convenu. Convoyage VE depuis Quimper.",
    date: "2026-09-01",
    image: "/images/mission-tesla.jpg",
    alt: "Tesla Model 3 en convoyage, plan de recharge",
    intro: "Un véhicule électrique ne se convoyage pas comme un thermique. Bornes, contrat, niveau de batterie.",
    body: [
      { h: "Le plan", p: "Trajet avec recharges. Plan B si une borne est hors service." },
      { h: "La remise", p: "Niveau convenu. Mise en main : charge, applications, câble du client." },
    ],
    faq: [{ q: "Fournissez-vous le câble ?", a: "Non, sauf s’il est dans le véhicule. Pas de promesse d’accessoire inventé." }],
    related: [{ to: "/convoyage-electrique", label: "VE" }, { to: "/simulateur", label: "Estimer" }],
  },
  {
    slug: "livraison-vehicule-electrique",
    title: "Livraison d’un véhicule électrique",
    h1: "Livraison d’un véhicule électrique",
    description: "Livraison VE, recharge, mise en main. Convoyage depuis Quimper pour particuliers et concessions.",
    date: "2026-09-01",
    image: "/images/blog-ve-livraison.jpg",
    alt: "Véhicule électrique en charge à domicile après livraison",
    intro: "Livrer un électrique, c’est livrer une autonomie, pas seulement une carrosserie.",
    body: [
      { h: "Concession", p: "Le client ne découvre pas une batterie à 8 %. Niveau convenu, pack lavage si besoin." },
      { h: "Particulier", p: "Mise en main offerte. Charge, options, applications." },
    ],
    faq: [{ q: "Surcoût ?", a: "Une option recharge entre dans la fourchette." }],
    related: [{ to: "/convoyage-electrique", label: "VE" }, { to: "/pack-mise-a-la-route", label: "Packs" }],
  },
  {
    slug: "preparation-vehicule-avant-livraison-client",
    title: "Préparation d’un véhicule avant livraison client",
    h1: "Préparation avant livraison client",
    description: "Pour les concessions : véhicule propre, contrôlé, documenté. Pack livraison client depuis Quimper.",
    date: "2026-09-01",
    image: "/images/blog-prep-concession.jpg",
    alt: "Préparation d’un BMW X3 en atelier de concession",
    intro: "Un commercial n’a pas à laver une voiture. Un préparateur n’a pas à faire Quimper–Rennes.",
    body: [
      { h: "Pack livraison client", p: "Convoyage, nettoyage, contrôle, photos, mise en main, compte-rendu." },
      { h: "Récurrence", p: "Compte professionnel, quinze jours, cadre volume." },
    ],
    faq: [{ q: "Délai type ?", a: "Selon créneau. Les rushs de fin de mois se cadrent." }],
    related: [{ to: "/professionnels", label: "Professionnels" }, { to: "/preparation-vehicule", label: "Préparation" }],
  },
  {
    slug: "externaliser-convoyage-concession",
    title: "Externaliser le convoyage automobile pour une concession",
    h1: "Externaliser le convoyage d’une concession",
    description: "Pourquoi une concession externalise ses convoyages. Gain de temps, traçabilité, livraison client. Quimper.",
    date: "2026-09-01",
    image: "/images/mission-bmw-x3.jpg",
    alt: "BMW X3 neuf, livraison client depuis une concession",
    intro: "Chaque trajet interne immobilise un vendeur. L’externaliser libère le banc et le showroom.",
    body: [
      { h: "Les cas", p: "Livraison client, inter-sites, VO, courtoisie, CT." },
      { h: "Le cadre", p: "Trois missions test, puis volume. Un interlocuteur. Des photos. Une facture." },
    ],
    faq: [{ q: "Abonnement ?", a: "Non imposé. À la mission, ou dégressif si le volume est cadré." }],
    related: [{ to: "/convoyage-concession", label: "Concessions" }, { to: "/professionnels", label: "Compte pro" }],
  },
  {
    slug: "garage-externaliser-convoyages",
    title: "Comment un garage peut externaliser ses convoyages",
    h1: "Garage : externaliser les convoyages",
    description: "CT, carrosserie, retours atelier. Un garage qui garde ses techniciens au banc. Convoyage depuis Quimper.",
    date: "2026-09-01",
    image: "/images/mission-golf-atelier.jpg",
    alt: "Volkswagen Golf déposée en atelier pour un garage",
    intro: "Un mécanicien sur la route ne répare rien. Un convoyeur, si.",
    body: [
      { h: "CT et carrosserie", p: "Aller-retour, EDL, créneau. Le client récupère sans que vous quittiez la fosse." },
      { h: "Volume", p: "Même logique concession. Compte professionnel." },
    ],
    faq: [{ q: "Utilitaires ?", a: "Oui, jusqu’à 3,5 t, permis B, vides." }],
    related: [{ to: "/convoyage-garage", label: "Garages" }, { to: "/professionnels", label: "Compte pro" }],
  },
  {
    slug: "convoyage-marchand-vo",
    title: "Comment fonctionne le convoyage pour un marchand VO",
    h1: "Convoyage pour marchand VO",
    description: "Rééquilibrage, livraisons, photos. Convoyage pour marchands de véhicules d’occasion, base Quimper.",
    date: "2026-09-01",
    image: "/images/blog-vo-lot.jpg",
    alt: "Parc de véhicules d’occasion, Audi, Volkswagen et BMW",
    intro: "Un VO mal placé ne se vend pas. Un VO mal documenté se discute.",
    body: [
      { h: "Photos", p: "L’EDL protège l’achat comme la vente. Rayures, pneus, compteur." },
      { h: "Flux", p: "Plates-formes, enchères, livraisons clients, retours." },
    ],
    faq: [{ q: "Import ?", a: "Oui. Allemagne, Belgique, Pologne. GPS souvent." }],
    related: [{ to: "/convoyage-marchand-vo", label: "Marchands VO" }, { to: "/convoyage-occasion", label: "Occasion" }],
  },
];

export function articleBySlug(slug: string) {
  return ARTICLES.find((a) => a.slug === slug);
}
