export const CONVOYAGE_STEPS = [
  {
    n: "01",
    title: "Ordre de mission",
    text: "Vous précisez le départ, l’arrivée, le véhicule et le créneau souhaité. Nous confirmons sous deux heures.",
  },
  {
    n: "02",
    title: "Prise en charge",
    text: "Un état des lieux photographique est établi : compteur, carrosserie, documents de bord. Le véhicule part ensuite.",
  },
  {
    n: "03",
    title: "Acheminement",
    text: "Un chauffeur dédié conduit le véhicule. L’assurance professionnelle s’applique. En cas d’imprévu, nous vous informons.",
  },
  {
    n: "04",
    title: "Remise",
    text: "Les clés sont remises en main propre à la personne désignée. La mise en main du véhicule est offerte.",
  },
  {
    n: "05",
    title: "Compte rendu",
    text: "Un rapport de mission est adressé le jour même : départ, arrivée, observations.",
  },
] as const;

export const CONVOYAGE_CATALOGUE = [
  {
    id: "france",
    kicker: "France",
    title: "Trajet point à point",
    text: "Le véhicule est pris en charge à l’adresse indiquée et remis au destinataire. Bretagne, Grand Ouest, Paris, Lyon, Nice. Intervention tous les jours, sous réserve de disponibilité.",
    items: [
      "Prise en charge à l’adresse du véhicule",
      "État des lieux photographique au départ et à l’arrivée",
      "Mise en main offerte à la remise",
      "Compte rendu adressé le jour même",
    ],
    image: "/images/mission-audi-a4.jpg",
    alt: "Audi A4 Avant en convoyage France",
  },
  {
    id: "achat",
    kicker: "Particulier",
    title: "Achat à distance",
    text: "Leboncoin, garage ou mandataire : le vendeur et l’acheteur n’ont pas à se déplacer. Nous récupérons le véhicule et le livrons à l’adresse convenue.",
    items: [
      "Contrôle visuel sur place avant le départ",
      "État des lieux photographique horodaté",
      "Remise au domicile ou sur le lieu de travail",
      "Présentation des aides à la conduite et du multimédia",
    ],
    image: "/images/mission-308.jpg",
    alt: "Peugeot 308 en convoyage entre particuliers",
  },
  {
    id: "europe",
    kicker: "Europe",
    title: "Import et export",
    text: "Belgique, Allemagne, Pologne, Monaco, Espagne, Italie, Royaume-Uni. Les documents sont vérifiés avant le départ. Un seul chauffeur, sans sous-traitance.",
    items: [
      "Vérification des documents avant le départ",
      "Passage de frontière préparé",
      "Suivi GPS pendant la mission, sur demande",
      "Remise en France et mise en main",
    ],
    image: "/images/mission-passat.jpg",
    alt: "Volkswagen Passat sur autoroute européenne",
  },
  {
    id: "livraison",
    kicker: "Professionnel",
    title: "Livraison client",
    text: "Concession, garage, mandataire. Le commercial demeure en établissement. Nous livrons le véhicule neuf ou d’occasion, assurons la mise en main et adressons le compte rendu au service donneur d’ordre.",
    items: [
      "Préparation et nettoyage selon la formule retenue",
      "Coffret de bienvenue selon la formule Livraison ou Signature",
      "Mise en main chez le client, vingt à trente minutes",
      "Facturation à quinze jours",
    ],
    image: "/images/mission-bmw-x3.jpg",
    alt: "BMW X3 neuve, livraison client",
  },
  {
    id: "atelier-pro",
    kicker: "Professionnel",
    title: "Navette d’atelier",
    text: "Contrôle technique, carrosserie, préparation. L’atelier conserve ses techniciens. Nous assurons les déplacements, y compris pour plusieurs véhicules sur un même créneau.",
    items: [
      "Approche depuis Quimper, intégrée au devis",
      "Photographies au départ et au retour",
      "Compte rendu adressé le soir",
      "Formule Atelier, sans coffret",
    ],
    image: "/images/mission-golf-atelier.jpg",
    alt: "Volkswagen Golf en navette atelier",
  },
  {
    id: "prestige",
    kicker: "Prestige",
    title: "Véhicules de prestige",
    text: "Sportive, collection, import de valeur. Clés et documents sous scellé, suivi GPS le temps de la mission, conduite adaptée, remise à la personne désignée. Il ne s’agit pas d’une activité de sécurité privée.",
    items: [
      "Clés et documents placés sous scellé",
      "Conduite en mode Comfort, autoroute privilégiée",
      "Pauses exclusivement en stations éclairées",
      "Compte rendu factuel, sans sous-traitance",
    ],
    image: "/images/mission-porsche-911.jpg",
    alt: "Porsche 911 en convoyage prestige",
  },
  {
    id: "retour",
    kicker: "Aller et retour",
    title: "Échange de véhicules",
    text: "Un véhicule à l’aller, un autre au retour : reprise, échange, deux adresses. Le second trajet est intégré au devis. Pas de retour à vide.",
    items: [
      "Deux prises en charge et deux remises",
      "État des lieux sur chaque véhicule",
      "Un même chauffeur, le jour même si le créneau le permet",
      "Approche et retours calculés depuis Quimper",
    ],
    image: "/images/mission-golf-brest.jpg",
    alt: "Volkswagen Golf 8 en convoyage",
  },
  {
    id: "electrique",
    kicker: "Électrique",
    title: "Véhicules électriques",
    text: "Tesla, hybrides rechargeables et tous véhicules électriques. Le plan de recharge est établi avant le départ. La mise en main porte aussi sur l’application et le câble.",
    items: [
      "Plan de recharge établi avant le départ",
      "Vérification du câble et du badge",
      "Mise en main de la charge à la remise",
      "Énergie facturée au réel, hors forfait",
    ],
    image: "/images/mission-tesla.jpg",
    alt: "Tesla Model 3 en convoyage",
  },
] as const;

export const CONVOYAGE_CLIENTS = [
  {
    id: "part",
    kicker: "Particulier",
    title: "Achat, vente, mutation",
    text: "Le véhicule est pris en charge et remis à l’adresse convenue. Trois formules : Route, Sérénité et Sécurisé. La mise en main est offerte.",
    to: "/simulateur",
    cta: "Demander un devis",
  },
  {
    id: "pro",
    kicker: "Professionnel",
    title: "Concessions, garages, mandataires",
    text: "Navettes d’atelier, livraisons clients et imports. Trois formules : Atelier, Livraison client et Signature réseau. Règlement à quinze jours.",
    to: "/simulateur",
    cta: "Demander un devis",
  },
] as const;