export const CONVOYAGE_STEPS = [
  {
    n: "01",
    title: "Le brief",
    text: "Départ, arrivée, créneau, véhicule. Vous validez. Nous confirmons sous deux heures.",
  },
  {
    n: "02",
    title: "La prise en charge",
    text: "Photos. Compteur. Carrosserie. Documents. Nous partons. Vous n’êtes pas au volant.",
  },
  {
    n: "03",
    title: "L’acheminement",
    text: "Un chauffeur. Une assurance. Un créneau tenu. Imprévu : nous appelons.",
  },
  {
    n: "04",
    title: "La remise",
    text: "Photos. Clés en main. Mise en main offerte. La personne nommée récupère le véhicule.",
  },
  {
    n: "05",
    title: "Le compte rendu",
    text: "Le soir même. Départ, arrivée, faits. Rien d’autre.",
  },
] as const;

export const CONVOYAGE_CATALOGUE = [
  {
    id: "france",
    kicker: "France",
    title: "A vers B",
    text: "Le véhicule est à un endroit. Le destinataire est à un autre. Nous faisons la route. Bretagne, Grand Ouest, Paris, Lyon, Nice. Tous les jours, si le créneau tient.",
    items: [
      "Prise en charge à l’adresse du véhicule",
      "Photos, compteur, carrosserie, documents",
      "Mise en main offerte à la remise",
      "Compte rendu le soir même",
    ],
    image: "/images/mission-audi-a4.jpg",
    alt: "Audi A4 Avant en convoyage France",
  },
  {
    id: "achat",
    kicker: "Particulier",
    title: "Achat à distance",
    text: "Leboncoin, garage, mandataire. Le vendeur ne vient pas. L’acheteur non plus. Nous allons chercher. Nous livrons. Un seul interlocuteur.",
    items: [
      "Contrôle visuel sur place avant de partir",
      "État des lieux photo horodaté",
      "Remise à domicile ou au travail",
      "Mise en main des aides et du multimédia",
    ],
    image: "/images/mission-308.jpg",
    alt: "Peugeot 308 en convoyage entre particuliers",
  },
  {
    id: "europe",
    kicker: "Europe",
    title: "Import, export",
    text: "Belgique, Allemagne, Pologne, Monaco, Espagne, Italie, Royaume-Uni. Les papiers avant la clé. Un chauffeur. Pas de sous-traitance.",
    items: [
      "Documents vérifiés avant le départ",
      "Passage de frontière cadré",
      "GPS le temps de la mission si demandé",
      "Remise en France, mise en main",
    ],
    image: "/images/mission-passat.jpg",
    alt: "Volkswagen Passat sur autoroute européenne",
  },
  {
    id: "livraison",
    kicker: "Professionnel",
    title: "Livraison client",
    text: "Concession, garage, mandataire. Le commercial reste en showroom. Nous livrons le VN ou le VO. Mise en main. Compte rendu au service qui commande.",
    items: [
      "Préparation et nettoyage selon le pack",
      "Coffret si Pack Livraison ou Signature",
      "Mise en main chez le client, 20 à 30 minutes",
      "Facture à quinze jours",
    ],
    image: "/images/mission-bmw-x3.jpg",
    alt: "BMW X3 neuve, livraison client",
  },
  {
    id: "atelier-pro",
    kicker: "Professionnel",
    title: "Navette atelier",
    text: "Contrôle technique, carrosserie, préparation. Les mécanos restent au banc. Nous faisons les allers-retours. Un créneau, plusieurs VL si besoin.",
    items: [
      "Approche depuis Quimper dans le devis",
      "Photos au départ et au retour",
      "Compte rendu le soir",
      "Pack Atelier. Pas de coffret.",
    ],
    image: "/images/mission-golf-atelier.jpg",
    alt: "Volkswagen Golf en navette atelier",
  },
  {
    id: "prestige",
    kicker: "Prestige",
    title: "Sportive, collection",
    text: "911, sportive, prestige, import de valeur. Scellés. GPS le temps de la mission. Conduite adaptée. Remise à la personne nommée. Ce n’est pas de la sécurité privée.",
    items: [
      "Clés et documents sous scellé",
      "Mode Comfort, autoroute privilégiée",
      "Pauses en stations éclairées",
      "Compte rendu factuel. Zéro sous-traitance",
    ],
    image: "/images/mission-porsche-911.jpg",
    alt: "Porsche 911 en convoyage prestige",
  },
  {
    id: "retour",
    kicker: "Aller et retour",
    title: "Un véhicule à reprendre",
    text: "Un à l’aller. Un autre au retour. Échange, reprise, deux adresses. Pas de rentrée à vide. Le second trajet est dans le devis.",
    items: [
      "Deux prises en charge, deux remises",
      "Photos sur chaque véhicule",
      "Même chauffeur, même journée si le créneau tient",
      "Approche et retours calculés depuis Quimper",
    ],
    image: "/images/mission-golf-brest.jpg",
    alt: "Volkswagen Golf 8 en convoyage",
  },
  {
    id: "electrique",
    kicker: "Électrique",
    title: "Recharge en route",
    text: "Tesla, hybride rechargeable, tout VE. Nous gérons les aires. Photos à chaque étape. Mise en main de l’application et du câble à l’arrivée.",
    items: [
      "Plan de recharge avant le départ",
      "Câble et badge vérifiés",
      "Mise en main de la charge à la remise",
      "Hors coût des kWh, facturés au réel",
    ],
    image: "/images/mission-tesla.jpg",
    alt: "Tesla Model 3 en convoyage",
  },
] as const;

export const CONVOYAGE_CLIENTS = [
  {
    id: "part",
    kicker: "Particulier",
    title: "Vous achetez. Vous vendez. Vous déménagez.",
    text: "Un véhicule à faire venir, ou à faire partir. Pack Route, Sérénité ou Sécurisé. Mise en main offerte.",
    to: "/simulateur",
    cta: "Devis particulier",
  },
  {
    id: "pro",
    kicker: "Professionnel",
    title: "Concession, garage, flotte.",
    text: "Navettes atelier, livraisons clients, imports. Pack Atelier, Livraison client ou Signature. Facture à quinze jours.",
    to: "/simulateur",
    cta: "Devis professionnel",
  },
] as const;