/** Noms de fichiers SEO. Une source pour tout le site. */
export const IMG = {
  hero: "/images/convoyage-berline-bretagne.jpg",
  heroPhares: "/images/convoyage-berline-phares.jpg",
  france: "/images/mission-golf-brest.jpg",
  europe: "/images/mission-passat.jpg",
  cles: "/images/mission-bmw-x3.jpg",
  prep: "/images/preparation-esthetique-vehicule.jpg",
  edl: "/images/mission-bmw-controle.jpg",
  gps: "/images/balise-gps-4g-vehicule.jpg",
  coffretBreton: "/images/coffret-terroir-breton.jpg",
  coffretChampagne: "/images/coffret-prestige-champagne.jpg",
  plein: "/images/plein-carburant-vehicule.jpg",
  garage: "/images/mission-golf-atelier.jpg",
  jockeyGare: "/images/mission-tiguan-gare.jpg",
  jockeyAero: "/images/mission-golf-aeroport.jpg",
  fondateur: "/images/fondateur-clement-quimper.jpg",
  securite: "/images/mission-ds7-vauban.jpg",
  prestige: "/images/mission-porsche-911.jpg",
  longTrajet: "/images/mission-audi-a4.jpg",
} as const;