/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as AvisRouteImport } from './routes/avis'
import { Route as CgvRouteImport } from './routes/cgv'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as LivraisonEuropeRouteImport } from './routes/livraison-europe'
import { Route as LivraisonVehiculeRouteImport } from './routes/livraison-vehicule'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as NettoyageVehiculeRouteImport } from './routes/nettoyage-vehicule'
import { Route as PrestationsRouteImport } from './routes/prestations'
import { Route as SimulateurRouteImport } from './routes/simulateur'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisRoute = AvisRouteImport.update({
  id: '/avis',
  path: '/avis',
  getParentRoute: () => rootRouteImport,
} as any)
const CgvRoute = CgvRouteImport.update({
  id: '/cgv',
  path: '/cgv',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const LivraisonEuropeRoute = LivraisonEuropeRouteImport.update({
  id: '/livraison-europe',
  path: '/livraison-europe',
  getParentRoute: () => rootRouteImport,
} as any)
const LivraisonVehiculeRoute = LivraisonVehiculeRouteImport.update({
  id: '/livraison-vehicule',
  path: '/livraison-vehicule',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const NettoyageVehiculeRoute = NettoyageVehiculeRouteImport.update({
  id: '/nettoyage-vehicule',
  path: '/nettoyage-vehicule',
  getParentRoute: () => rootRouteImport,
} as any)
const PrestationsRoute = PrestationsRouteImport.update({
  id: '/prestations',
  path: '/prestations',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulateurRoute = SimulateurRouteImport.update({
  id: '/simulateur',
  path: '/simulateur',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/a-propos': typeof AProposRoute
  '/avis': typeof AvisRoute
  '/cgv': typeof CgvRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/livraison-europe': typeof LivraisonEuropeRoute
  '/livraison-vehicule': typeof LivraisonVehiculeRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/nettoyage-vehicule': typeof NettoyageVehiculeRoute
  '/prestations': typeof PrestationsRoute
  '/simulateur': typeof SimulateurRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/a-propos': typeof AProposRoute
  '/avis': typeof AvisRoute
  '/cgv': typeof CgvRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/livraison-europe': typeof LivraisonEuropeRoute
  '/livraison-vehicule': typeof LivraisonVehiculeRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/nettoyage-vehicule': typeof NettoyageVehiculeRoute
  '/prestations': typeof PrestationsRoute
  '/simulateur': typeof SimulateurRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/a-propos': typeof AProposRoute
  '/avis': typeof AvisRoute
  '/cgv': typeof CgvRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/livraison-europe': typeof LivraisonEuropeRoute
  '/livraison-vehicule': typeof LivraisonVehiculeRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/nettoyage-vehicule': typeof NettoyageVehiculeRoute
  '/prestations': typeof PrestationsRoute
  '/simulateur': typeof SimulateurRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/a-propos'
    | '/avis'
    | '/cgv'
    | '/confidentialite'
    | '/contact'
    | '/livraison-europe'
    | '/livraison-vehicule'
    | '/mentions-legales'
    | '/nettoyage-vehicule'
    | '/prestations'
    | '/simulateur'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/a-propos'
    | '/avis'
    | '/cgv'
    | '/confidentialite'
    | '/contact'
    | '/livraison-europe'
    | '/livraison-vehicule'
    | '/mentions-legales'
    | '/nettoyage-vehicule'
    | '/prestations'
    | '/simulateur'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/a-propos'
    | '/avis'
    | '/cgv'
    | '/confidentialite'
    | '/contact'
    | '/livraison-europe'
    | '/livraison-vehicule'
    | '/mentions-legales'
    | '/nettoyage-vehicule'
    | '/prestations'
    | '/simulateur'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  AProposRoute: typeof AProposRoute
  AvisRoute: typeof AvisRoute
  CgvRoute: typeof CgvRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  ContactRoute: typeof ContactRoute
  LivraisonEuropeRoute: typeof LivraisonEuropeRoute
  LivraisonVehiculeRoute: typeof LivraisonVehiculeRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  NettoyageVehiculeRoute: typeof NettoyageVehiculeRoute
  PrestationsRoute: typeof PrestationsRoute
  SimulateurRoute: typeof SimulateurRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avis': {
      id: '/avis'
      path: '/avis'
      fullPath: '/avis'
      preLoaderRoute: typeof AvisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgv': {
      id: '/cgv'
      path: '/cgv'
      fullPath: '/cgv'
      preLoaderRoute: typeof CgvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livraison-europe': {
      id: '/livraison-europe'
      path: '/livraison-europe'
      fullPath: '/livraison-europe'
      preLoaderRoute: typeof LivraisonEuropeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livraison-vehicule': {
      id: '/livraison-vehicule'
      path: '/livraison-vehicule'
      fullPath: '/livraison-vehicule'
      preLoaderRoute: typeof LivraisonVehiculeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nettoyage-vehicule': {
      id: '/nettoyage-vehicule'
      path: '/nettoyage-vehicule'
      fullPath: '/nettoyage-vehicule'
      preLoaderRoute: typeof NettoyageVehiculeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prestations': {
      id: '/prestations'
      path: '/prestations'
      fullPath: '/prestations'
      preLoaderRoute: typeof PrestationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulateur': {
      id: '/simulateur'
      path: '/simulateur'
      fullPath: '/simulateur'
      preLoaderRoute: typeof SimulateurRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  AProposRoute: AProposRoute,
  AvisRoute: AvisRoute,
  CgvRoute: CgvRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  ContactRoute: ContactRoute,
  LivraisonEuropeRoute: LivraisonEuropeRoute,
  LivraisonVehiculeRoute: LivraisonVehiculeRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  NettoyageVehiculeRoute: NettoyageVehiculeRoute,
  PrestationsRoute: PrestationsRoute,
  SimulateurRoute: SimulateurRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
